FROM haskell:9.2.5
# Version from build arg
ARG app_version
ENV APP_VERSION=$app_version

# Dependencies for caching
WORKDIR /opt/app
COPY feedfarer.cabal stack.yaml .
RUN stack --resolver lts-20.9 test \
  --install-ghc \
  --no-library-profiling \
  --fast \
  --no-run-tests \
  --only-dependencies

COPY . . 
COPY /static /var/www/feedfarer-webui

# Build and run tests
CMD ["stack", "--resolver", "lts-20.9", "test", "--fast"]
