FROM haskell:latest
ARG app_version=test
ENV APP_VERSION=$app_version
WORKDIR /opt/app

# Dependencies for caching
COPY feedfarer.cabal stack.yaml .
RUN stack --resolver lts-19.33 test \
  --install-ghc \
  --no-library-profiling \
  --fast \
  --no-run-tests \
  --only-dependencies

COPY ./app app/
COPY ./src src/
COPY ./test test/
COPY ./Setup.hs ./package.yaml .
COPY /static /var/www/feedfarer-webui

# Build and run tests
CMD ["stack", "--resolver", "lts-19.33", "test", "--fast"]
