name: GitHub Test suite

on: 
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment: production
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build & run tests
      shell: bash
      run: |
        BASE_URL=$BASE_URL
        echo $BASE_URL
        echo BASE_URL
        echo '${{ env.BASE_URL }}'
        docker-compose -f test-build.yml up \
          --abort-on-container-exit